import type { Metadata } from "next";
import {
  Federant,
  Geist,
  Geist_Mono,
  Inter,
  Lobster_Two,
} from "next/font/google";
import "./globals.css";
import Providers from "./components/organisms/providers/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const federant = Federant({
  subsets: ["latin"],
  variable: "--font-federant",
  weight: "400",
});

const lobsterTwo = Lobster_Two({
  subsets: ["latin"],
  variable: "--font-lobster",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Difu's Thought Corner",
  description: "Generated by create next app, but fr created by HIM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${federant.variable} ${lobsterTwo.variable} h-full antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
